# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1d1d8e0f94673545d15b8fa2ef33bc5"
name = "Ecom Speed Experts"
application_url = "https://01c4c75e0af3.ngrok-free.app"
embedded = true
handle = "ecom-speed-experts-2"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_payment_methods,read_orders,read_products,write_own_subscription_contracts,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://01c4c75e0af3.ngrok-free.app/auth/callback",
  "https://01c4c75e0af3.ngrok-free.app/auth/shopify/callback",
  "https://01c4c75e0af3.ngrok-free.app/api/auth/callback"
]
