# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1d1d8e0f94673545d15b8fa2ef33bc5"
name = "Ecom Speed Experts"
application_url = "https://boringly-dashiest-minh.ngrok-free.dev"
embedded = true
handle = "ecom-speed-experts-2"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions/update"


[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "/webhooks/app/customers/data_request"
[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "/webhooks/app/customers/redact"
[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "/webhooks/app/shop/redact"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_payment_methods,read_orders,read_products,write_own_subscription_contracts,write_products,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://boringly-dashiest-minh.ngrok-free.dev/auth/callback",
  "https://boringly-dashiest-minh.ngrok-free.dev/auth/shopify/callback",
  "https://boringly-dashiest-minh.ngrok-free.dev/api/auth/callback"
]
