# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "45c40a9fea1e1dd99ce513e99da6f059"
name = "buy-plan-2"
application_url = "https://marceline-unsympathizing-lauri.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"


  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions/update"
  
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,read_themes,write_themes,read_themes"

[auth]
redirect_urls = [
  "https://marceline-unsympathizing-lauri.ngrok-free.dev/auth/callback",
  "https://marceline-unsympathizing-lauri.ngrok-free.dev/auth/shopify/callback",
  "https://marceline-unsympathizing-lauri.ngrok-free.dev/api/auth/callback"
]